apiVersion: apps/v1
kind: Deployment
metadata:
  name: testjenkins-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testjenkins
  template:
    metadata:
      labels:
        app: testjenkins
    spec:
      containers:
        - name: testjenkins
          image: tvenencia/testjenkins-pipeline:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
