apiVersion: v1
kind: Service
metadata:
  name: testjenkins-service
  labels:
    app: testjenkins
spec:
  selector:
    app: testjenkins

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
